### ISSUE TITLE
Parnters

### ISSUE THREAD

**Issue by naeemadam** [loogart/leburgerweek#12]
Can we remove the current partners and just add the following:

- Budweiser
- Just Eat
- Skip the Dishes
- Hellmann's

**Comment by loogart** [comment]
<img width="1106" alt="screen shot 2017-06-30 at 2 06 41 pm" src="https://user-images.githubusercontent.com/7881400/27748413-5f772b60-5d9d-11e7-9ff7-7d34ffb5cfac.png">

**Comment by naeemadam** [comment]
looks good!!
