### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by naeemadam** [loogart/leburgerweek#14]
I think we might have to add another page where people can learn about things. 

One page with mainly text and when people want to learn more about Bud and Burgers, Just Eat or Buy a Friend a burger, it’s all there. Let me know if that is possible. They can click "learn more" on the index jumbo images and go to that secton of the page. We can also have the FAQ in the footer.

**Comment by loogart** [comment]
@naeemadam do you want this to be an "About" page? I would avoid the FAQ in the footer, put it in the about page for now.

**Comment by naeemadam** [comment]
Yes - sure!

**Comment by loogart** [comment]
![screen shot 2017-06-30 at 2 45 11 pm](https://user-images.githubusercontent.com/7881400/27749735-bda00392-5da2-11e7-93c4-246616b80429.png)
created an about.html page where you can put info, FAQ, different info sections about LBW. It'a a generic page that you can customize to whatever you want @naeemadam
