### ISSUE TITLE
Facebook Cover

### ISSUE THREAD

**Issue by naeemadam** [loogart/leburgerweek#15]
Can we get Banner 1 from Index for our Facebook cover?

**Comment by loogart** [comment]
@naeemadam for shizzle my nizzle, I will actually create the formatted FB cover. Which logo version do you want to use btw?

**Comment by naeemadam** [comment]
No logo, just your art work.

**Comment by loogart** [comment]
<img width="1097" alt="screen shot 2017-06-30 at 1 31 36 pm" src="https://user-images.githubusercontent.com/7881400/27747476-446fdac8-5d99-11e7-8cbe-f828bec44b42.png">
<img width="1100" alt="screen shot 2017-06-30 at 1 17 03 pm" src="https://user-images.githubusercontent.com/7881400/27747477-447e4f54-5d99-11e7-8b06-19e38d9e9166.png">
