### ISSUE TITLE
Main Logo

### ISSUE THREAD

**Issue by naeemadam** [loogart/leburgerweek#16]
- I think we should replace the little logo on the top left corner with the “brandless” English logo. It just doesn’t look good there. The same one we used for the Favicon.
- Is three a place where we can put the main logo? Maybe in the footer? It’s not really visible anywhere else.

**Comment by loogart** [comment]
- Brandless EN logo added to navbar
- i added the main logo on the first jumbotron slide and in the footer

![127 0 0 1-51108-index html iphone 5](https://user-images.githubusercontent.com/7881400/27719605-9ec0b3e4-5d21-11e7-8a3a-cd648278acc5.png)
![screen shot 2017-06-29 at 11 20 20 pm](https://user-images.githubusercontent.com/7881400/27719604-9ec00c0a-5d21-11e7-9d28-1b06cb4dbef0.png)
![screen shot 2017-06-29 at 11 19 53 pm](https://user-images.githubusercontent.com/7881400/27719630-bec0913c-5d21-11e7-9db6-37099c553be3.png)
![screen shot 2017-06-29 at 11 22 01 pm](https://user-images.githubusercontent.com/7881400/27719636-c6a037b8-5d21-11e7-906e-f42051f48d88.png)
