### ISSUE TITLE
Cities

### ISSUE THREAD

**Issue by naeemadam** [loogart/leburgerweek#18]
Can we add all the other cities?

**Comment by loogart** [comment]
@naeemadam is this the full list? And let me know if you have specific photos for each one (I just bought several off Shutterstock for the prototype design).

1. Montreal
2. Saskatoon
3. Toronto
4. Ottawa
5. Regina
6. Clagary
7. Edmonton
8. Victoria
9. Vancouver
10. Omaha
11. Cleveland
12. Buffalo
13. Port-au-Prince
14. Cap Haitien
15. Quebec
16. Winnipeg

**Comment by loogart** [comment]
All cities added (as per the staging site by Mat). Several cities still need photography.

![screen shot 2017-06-29 at 11 20 01 pm](https://user-images.githubusercontent.com/7881400/27719667-e90e0a14-5d21-11e7-846c-a02597855595.png)
![screen shot 2017-06-29 at 11 20 04 pm](https://user-images.githubusercontent.com/7881400/27719668-e9102d6c-5d21-11e7-9538-6f1b2e3ec79a.png)
