### ISSUE TITLE
All pages: mobile padding

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#19]
MAJOR: All mobile pages seem to have padding to its right - affects mainly iPhone 5 and 6.
![peoplemover-staging ca-central-1 elasticbeanstalk com- iphone 5](https://user-images.githubusercontent.com/7881400/27838499-13073a3a-60b9-11e7-9d95-4288cbe93a6b.png)

**Comment by matbalazsi** [comment]
partially fixed. Issue remains when the city name is extra long and overflows, but this will not occur with the cities we are using
