### ISSUE TITLE
All pages: navbar dropdown animations

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#21]
Navbar dropdown animations - using old boostrap 3 javascript - might need to invoke specific dropdown javascript?

![screen shot 2017-07-04 at 1 04 10 pm](https://user-images.githubusercontent.com/7881400/27838531-4940a1d6-60b9-11e7-858d-93ae7fdc5409.png)

**Comment by matbalazsi** [comment]
fixed
