### ISSUE TITLE
All pages: mobile menu padding + close btn

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#23]
MAJOR: Mobile view: Mobile menu has padding around it + close button alignment is reversed to the right instead of the left

![peoplemover-staging ca-central-1 elasticbeanstalk com- iphone 5 1](https://user-images.githubusercontent.com/7881400/27838572-894d2312-60b9-11e7-8995-7398de018668.png)

**Comment by matbalazsi** [comment]
fixes

**Comment by loogart** [comment]
@matbalazsi almost there, maybe there's some css that is off (when you scroll on a smaller phone). Check the css from .mobile-menu for all ul and li elements.

![peoplemover-staging ca-central-1 elasticbeanstalk com- iphone 5](https://user-images.githubusercontent.com/7881400/28289869-5519873a-6b12-11e7-8345-0a536a5c2397.png)

**Comment by matbalazsi** [comment]
The behavior is consistent with the design code. Perhaps we should make the list scrollable and not the entire modal?

**Comment by loogart** [comment]
There seems to be 2 "modal-content" divs (one inside of the other). Also, is there a way to wrap the modal with a <section class="mobile-menu">? The default behaviour of the BS modal should stay scrollable. @matbalazsi 

![screen shot 2017-07-21 at 11 13 35 am](https://user-images.githubusercontent.com/7881400/28469883-c2ea1f2c-6e05-11e7-8ebe-b2189d1d6e1c.png)
