### ISSUE TITLE
All pages: footer mobile layout

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#25]
Footer columns are staying at 3 columns, see html prototype

![peoplemover-staging ca-central-1 elasticbeanstalk com- iphone 5 2](https://user-images.githubusercontent.com/7881400/27838614-cf7db234-60b9-11e7-9bf5-adeb2a3776a6.png)

**Comment by matbalazsi** [comment]
fixed

**Comment by loogart** [comment]
@matbalazsi don't want to be picky, but there seems to be line height or margin issues for the footer as well. The grid layout is fixed though! awesome.

![screen shot 2017-07-17 at 5 10 20 pm](https://user-images.githubusercontent.com/7881400/28290037-d8b19ba0-6b12-11e7-816a-237161193beb.png)

**Comment by matbalazsi** [comment]
fixed. Again an issue with default margin-top of h3
