### ISSUE TITLE
All pages: logo css

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#26]
Burger logo css updated to enhance size of logo
![screen shot 2017-07-04 at 1 08 59 pm](https://user-images.githubusercontent.com/7881400/27838631-f591b97a-60b9-11e7-9677-c4f530be599e.png)
![screen shot 2017-07-04 at 1 09 10 pm](https://user-images.githubusercontent.com/7881400/27838636-fd673710-60b9-11e7-9a1f-a367287ebab8.png)

**Comment by matbalazsi** [comment]
fixed
