### ISSUE TITLE
All pages: footer hr line

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#27]
Footer hr line is black, should be white as in the second image
![screen shot 2017-07-04 at 1 10 06 pm](https://user-images.githubusercontent.com/7881400/27838655-1c49b090-60ba-11e7-85c3-74bf869b662b.png)
![screen shot 2017-07-04 at 1 10 14 pm](https://user-images.githubusercontent.com/7881400/27838659-2174f6a6-60ba-11e7-8762-7fb651e000ce.png)

**Comment by matbalazsi** [comment]
fixed
