### ISSUE TITLE
All pages: Favicon

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#28]
MAJOR: Add favicon (see my header html code which should cover most Browsers)
![screen shot 2017-07-04 at 1 11 07 pm](https://user-images.githubusercontent.com/7881400/27838683-43221b26-60ba-11e7-9fd6-6d49121b3031.png)

code:
`    
    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="img/favicon.png">

    
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Le Burger Week">
    <link rel="apple-touch-icon-precomposed" href="img/favicon.png">

    
    <meta name="msapplication-TileImage" content="img/favicon.png">
    <meta name="msapplication-TileColor" content="#FF7525">
    <link rel="shortcut icon" href="img/favicon.png">
    <link rel="mask-icon" href="img/icons/safari-pinned-tab.svg" color="#FF7525">
    <meta name="theme-color" content="#FF7525">

    
    <link href="css/bootstrap.css" rel="stylesheet">
    <link href="css/owl.carousel.css" rel="stylesheet">
    <link href="css/owl.theme.default.css" rel="stylesheet">
    <link href="css/animate.css" rel="stylesheet">
    <link href="css/magnific-popup.css" rel="stylesheet">
    <link href="css/styles.css" rel="stylesheet">`

**Comment by matbalazsi** [comment]
this was already in the code. How can I reproduce the issue?

**Comment by loogart** [comment]
@matbalazsi if you look on chrome or safari (or most web browsers), the favicon is not there (as in the image I attached)

**Comment by matbalazsi** [comment]
The issue exists on the staging but cannot reproduce locally. 
Could it be the size of the png? 298x298

Should we try a 32x32 .ico?

Also, we do not have
assets/images/icons/safari-pinned-tab.svg

**Comment by loogart** [comment]
@matbalazsi it works on the github hosted website with the current assets for the favicon. I use only pngs now for favicon, ico is mostly for backwards compatibility to older browsers (IE6).
