### ISSUE TITLE
All pages: City dropdown scroll 

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#29]
MAJOR: Dropdown scroll for cities (need to implement the new css to enable scroll beyond the y-overflow). See bottom image.

![screen shot 2017-07-04 at 1 13 07 pm](https://user-images.githubusercontent.com/7881400/27838748-88b7e832-60ba-11e7-9479-cd52137be6a1.png)
![screen shot 2017-07-04 at 1 13 00 pm](https://user-images.githubusercontent.com/7881400/27838749-88b8b9b0-60ba-11e7-960e-9f9b3eac0ba4.png)

Add .scrollable-menu css to dropdown menu:

`.scrollable-menu {
    height: auto;
    max-height: 80vh;
    overflow-x: hidden;
}`

The html would look like this: 

`<ul class="dropdown-menu scrollable-menu" aria-labelledby="dropdownMenu1">  ... </ul>`

**Comment by matbalazsi** [comment]
fixed
