### ISSUE TITLE
Index: Navbar city selector default

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#30]
MAJOR: When you return to home page, default location should be "Select your city", like in the bottom image
![screen shot 2017-07-04 at 1 15 52 pm](https://user-images.githubusercontent.com/7881400/27838812-ed6c35b2-60ba-11e7-967c-5dfd72197d54.png)

![screen shot 2017-07-04 at 1 15 56 pm](https://user-images.githubusercontent.com/7881400/27838811-ed6a7ace-60ba-11e7-85b5-ad8f918a5a51.png)

**Comment by matbalazsi** [comment]
partially fixed - caret stays orange when no city selected

**Comment by loogart** [comment]
@matbalazsi stays orange only on hover, you're like 95% there lol

**Comment by matbalazsi** [comment]
fixed
