### ISSUE TITLE
Index: Jumbotron padding

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#31]
Jumbotron: bottom (and probably top) of jumbotron still has Boostrap's rounded corners

Also, the image should take the full height of the carousel - double check in the css (might have updated it)

Compare both images, should be like the one below.

![screen shot 2017-07-04 at 1 22 18 pm](https://user-images.githubusercontent.com/7881400/27838948-d594090a-60bb-11e7-8ba1-a6fa7dafad8a.png)
![screen shot 2017-07-04 at 1 22 21 pm](https://user-images.githubusercontent.com/7881400/27838947-d5884d7c-60bb-11e7-94ed-9ab80d7dca8a.png)

**Comment by matbalazsi** [comment]
did not see any change in css. Is it from styles.scss .main-jumbotron{} ?

**Comment by loogart** [comment]
@matbalazsi I'm not sure, I'll check in the html as well, gotta so some more investigating on my end as well
