### ISSUE TITLE
Index: jumbotron rounded corners

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#33]
Jumbotron: bottom (and probably top) of jumbotron still has Boostrap's rounded corners

![screen shot 2017-07-04 at 1 19 22 pm](https://user-images.githubusercontent.com/7881400/27838883-690b4e42-60bb-11e7-8e44-91d51887cbf4.png)
![screen shot 2017-07-04 at 1 19 16 pm](https://user-images.githubusercontent.com/7881400/27838884-6a58fef2-60bb-11e7-90d3-4a3a73b9cd0c.png)

**Comment by matbalazsi** [comment]
fixed
