### ISSUE TITLE
Index: City image grid to update

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#34]
Update grid layout for col-md to 3 columns, col-sm to 2 columns - see bottom image

![screen shot 2017-07-04 at 1 23 24 pm](https://user-images.githubusercontent.com/7881400/27838976-fa9bec04-60bb-11e7-8f9a-94987bc096af.png)
![screen shot 2017-07-04 at 1 23 29 pm](https://user-images.githubusercontent.com/7881400/27838975-fa9b2152-60bb-11e7-9d3c-77a2ccbb57f7.png)

**Comment by matbalazsi** [comment]
fixed
