### ISSUE TITLE
City: Top jumbotron border radius

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#35]
MAJOR: Top jumbotron has border radius, remove border radius as per bottom image:

![screen shot 2017-07-04 at 1 25 30 pm](https://user-images.githubusercontent.com/7881400/27839010-450ddcca-60bc-11e7-943f-77191a344035.png)

![screen shot 2017-07-04 at 1 25 34 pm](https://user-images.githubusercontent.com/7881400/27839011-450f5b54-60bc-11e7-93d1-e9d89875ce11.png)

**Comment by matbalazsi** [comment]
fixed
