### ISSUE TITLE
City: burger grid layout

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#36]
MAJOR: Adjust grid layout - when col-sm, should be 2 columns not 3
![screen shot 2017-07-04 at 1 26 37 pm](https://user-images.githubusercontent.com/7881400/27839047-82ac3374-60bc-11e7-9ae9-e33db5653f82.png)
![screen shot 2017-07-04 at 1 26 35 pm](https://user-images.githubusercontent.com/7881400/27839046-82a1d2b2-60bc-11e7-969a-b395bb88fac9.png)

**Comment by matbalazsi** [comment]
fixed. Please review on next staging

**Comment by loogart** [comment]
@matbalazsi col-sm-6 still not showing up

**Comment by matbalazsi** [comment]
updated. Bootsrtap4 vs 3 col widths are different so diffictult to reproduce exactly
