### ISSUE TITLE
City: open burger in new tab

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#37]
When you click on a burger, it should open a NEW tab - good UX practice used by Airbnb and Foursquare to open multiple tabs and "bookmark" the burgers you want to view
![screen shot 2017-07-04 at 1 28 11 pm](https://user-images.githubusercontent.com/7881400/27839068-a28278d4-60bc-11e7-832b-598ca496de3a.png)

**Comment by matbalazsi** [comment]
issue with @uirouter/angular

**Comment by loogart** [comment]
opening the Burgers in a new tab is waiting on 
https://github.com/angular-ui/ui-router

**Comment by loogart** [comment]
@matbalazsi this is a no fix issue for the time-being?
