### ISSUE TITLE
Burger: Subtitles and social links

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#39]
Missing secondary titles and social media links (I assume they don't show up unless they exist in the database) -- should be like below image

![screen shot 2017-07-04 at 1 30 23 pm](https://user-images.githubusercontent.com/7881400/27839125-f3326b18-60bc-11e7-96eb-df2824ad3253.png)
![screen shot 2017-07-04 at 1 30 26 pm](https://user-images.githubusercontent.com/7881400/27839126-f3328724-60bc-11e7-83e4-2b146b84ea23.png)

**Comment by matbalazsi** [comment]
They only show up if set in the database. I will provide a working example
