### ISSUE TITLE
Main logo and text

### ISSUE THREAD

**Issue by naeemadam** [loogart/leburgerweek#4]
Always have it be "Le Burger Week" and in one color, or consistent always everywhere.

![screen shot 2017-06-26 at 12 50 02 pm](https://user-images.githubusercontent.com/29712323/27550564-2e9c46ba-5a6e-11e7-9502-56c9ec00da10.png)

**Comment by loogart** [comment]
![127 0 0 1-64505-index html iphone 6](https://user-images.githubusercontent.com/7881400/27642423-c0d654f6-5bec-11e7-83be-4af1321f263c.png)
![screen shot 2017-06-28 at 10 29 23 am](https://user-images.githubusercontent.com/7881400/27642424-c0ddab2a-5bec-11e7-8104-90a4e150617d.png)
