### ISSUE TITLE
Burger: Minor margin above map

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#40]
Margin between the burger description panel and the map -- see below image

![screen shot 2017-07-04 at 1 30 23 pm](https://user-images.githubusercontent.com/7881400/27839151-11b6d772-60bd-11e7-9dd1-2f69b5944905.png)
![screen shot 2017-07-04 at 1 30 26 pm](https://user-images.githubusercontent.com/7881400/27839150-11b30afc-60bd-11e7-812f-3df905778a30.png)

**Comment by matbalazsi** [comment]
fixed
