### ISSUE TITLE
Burger: Carousel and lightbox

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#41]
MAJOR: Carousel and lightbox for burger photos not working/actived, should look like below and have the zoom capacity of the lightbox.

![screen shot 2017-07-04 at 1 32 22 pm](https://user-images.githubusercontent.com/7881400/27839172-3a86a506-60bd-11e7-8726-43686bb4f54e.png)
![screen shot 2017-07-04 at 1 32 46 pm](https://user-images.githubusercontent.com/7881400/27839174-45c3289a-60bd-11e7-97a5-5eb3bac9b2fe.png)

**Comment by matbalazsi** [comment]
fixed

**Comment by loogart** [comment]
2 questions: can they upload more than 1 image (functionality) and will the image take full width if resolution permits?

![peoplemover-staging ca-central-1 elasticbeanstalk com-restaurants-suzette-bistro-view iphone 5 1](https://user-images.githubusercontent.com/7881400/28288255-a504e7d6-6b0c-11e7-927f-0f6af7c93fc2.png)

**Comment by matbalazsi** [comment]
we do not have multiple images per burger. Also, lightbox was not working on Angular4, so I made a simple modal. 
The modal looks better on mobile now
