### ISSUE TITLE
Burger: mobile bottom bar

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#42]
MAJOR: On mobile, the css media query should kick in to have the bottom action bar (not visible on desktop), see bottom image

![peoplemover-staging ca-central-1 elasticbeanstalk com-restaurants-yatai-japanese-street-food-view iphone 5](https://user-images.githubusercontent.com/7881400/27839191-76aad854-60bd-11e7-8724-3f6d556a2582.png)
![loogart github io-leburgerweek-burger html iphone 5](https://user-images.githubusercontent.com/7881400/27839194-77d208e2-60bd-11e7-9822-4514528ac9b7.png)

**Comment by matbalazsi** [comment]
fixed

**Comment by loogart** [comment]
Need to keep button orange and text should be "Buy this for a friend"

![peoplemover-staging ca-central-1 elasticbeanstalk com-restaurants-suzette-bistro-view iphone 5](https://user-images.githubusercontent.com/7881400/28288180-5700aa0c-6b0c-11e7-8346-898c84c884e9.png)

**Comment by matbalazsi** [comment]
fixed

**Comment by loogart** [comment]
@matbalazsi on iPhone 5, the buttons have too much padding causing them to stack one on top of the other. If you could change the following css, it would fix it

.btn {
   font-size: 14px;
   padding: 6px 12px;
   line height: 1.42857143;
}

![peoplemover-staging ca-central-1 elasticbeanstalk com-restaurants-osheas-irish-pub-view iphone 5](https://user-images.githubusercontent.com/7881400/28469197-7e8d1192-6e03-11e7-920a-5a0b6a420465.png)
:
