### ISSUE TITLE
Burger: Footer not necessary

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#43]
Footer section is not necessary since we want people to focus on the burgers open in the new tab _ especially on mobile (no need additional scrolling caused by the footer), should be like bottom image

![screen shot 2017-07-04 at 1 35 23 pm](https://user-images.githubusercontent.com/7881400/27839215-a4fb53a0-60bd-11e7-9456-f9dc72e91e7c.png)
![screen shot 2017-07-04 at 1 35 20 pm](https://user-images.githubusercontent.com/7881400/27839216-a4fb7042-60bd-11e7-850c-3e338df7d731.png)

On mobile, scrolled all the way down, footer is not necessary:

![screen shot 2017-07-04 at 1 36 06 pm](https://user-images.githubusercontent.com/7881400/27839226-c7b7bb0e-60bd-11e7-9192-6e177a592000.png)

**Comment by matbalazsi** [comment]
fixed
