### ISSUE TITLE
Burger: Line heights for burger titles

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#45]
Line heights for title and subtitle of burgers need to be adjusted according to original design.

![screen shot 2017-07-17 at 4 19 06 pm](https://user-images.githubusercontent.com/7881400/28288132-2255dda4-6b0c-11e7-811f-5541b39cc29a.png)

**Comment by matbalazsi** [comment]
fixed. was an issue with default margin-top and margin-bottom of h3 and h5 tags
