### ISSUE TITLE
Home: City titles on tiles to fix

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#46]
Font on tiles is slightly bigger (e.g. Port au Prince cuts out of the tile). Reduce slightly to ensure it fits in. Also use css property `word-wrap: break-word;` to make it wrap even with hyphens. I can rewrite this with Flexbox as well is it is easier

![screen shot 2017-07-18 at 10 47 09 am](https://user-images.githubusercontent.com/7881400/28323366-90fae93a-6ba6-11e7-8d1e-80882dc07bfd.png)
![screen shot 2017-07-18 at 10 47 36 am](https://user-images.githubusercontent.com/7881400/28323367-91003f02-6ba6-11e7-8d39-11bb9befbca0.png)

**Comment by matbalazsi** [comment]
word-wrap: break-word; was not working, since .tile h3{position:absolute}
for now reducing the font-size from 2.5em to 2.2em

**Comment by loogart** [comment]
@matbalazsi you can reduce it to 2em even! The Laval - Rive Sud acts up when the viewport gets bigger. That should close this issue.
