### ISSUE TITLE
Registration Page: Email to pay by cheque link

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#54]
Registration page: For the small text about paying by cheque before the green "pay and register" button, add the following url to create a basic pre-populated email for users.

`<a href="href="mailto:stephanie@peoplemovertech.com?cc=thierry@peoplemovertech.com, jp@peoplemovertech.com&subject=Le%20Burger%20Week%202019%20Registration&body=Hi, my name is ___ and I would like to register our restaurant ___ to the 2019 Le Burger Week.I would also like to pay by cheque. What are the next steps? My phone number is ___. Thank you.">email us directly</a>`

**Comment by matbalazsi** [comment]
Sure. What about french users?

**Comment by matbalazsi** [comment]
Updated, but need to test.
edit: Tested
