### ISSUE TITLE
Homepage: Safari Fixed Navbar

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#55]
Homepage: Safari: pull the latest sass file (added -webkit-sticky to the position of the navbar, consistent with Chrome)

**Comment by matbalazsi** [comment]
It was already there. Could it be a different issue?

**Comment by loogart** [comment]
I tried manipulating the DOM in Safari, but the only thing I could do to fix the sticky is to move the navbar outside of the `<app-navbar>` section. I assume this is an Angular structure.
