### ISSUE TITLE
Login page: Input validation to add

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#59]
Log in page: I can add the default validation from BS4 like in the registration page for mandatory fields - on staging site, it doesn't prompt the user that they should fill out fields if they click login without filling up the fields.

**Comment by matbalazsi** [comment]
We are using Reactive Forms. Maybe we can talk to discuss how BS4 does this.
The fields become red if they are invalid

**Comment by loogart** [comment]
Can we implement the simple BS4 browser default like here?
https://getbootstrap.com/docs/4.3/components/forms/#browser-defaults

That's what I implemented for the prototype: https://loogart.github.io/leburgerweek/2019/register.html
