### ISSUE TITLE
Burger Page: Close tab behaviour

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#69]
Once a user hits the "back to burgers" link, it should close the current browser tab and bring the user back to the original results page: https://stackoverflow.com/questions/2076299/how-to-close-current-tab-in-a-browser-window

**Comment by matbalazsi** [comment]
I dont think i can close a tab through a button. What if the user arrived at the burger via an external link? I don't think we should asdume a second tab was open

**Comment by loogart** [comment]
Very good point - arriving from an external link. I guess, leave it there. keep it simple.

**Comment by loogart** [comment]
I’m thinking about it more, to simplify further, I’d remove the whole breadcrumb with “ back to burgers”. People will have it opened in a new tab or will arrive from an external link - they will click back on the logo for home if they need to.
