### ISSUE TITLE
Burger Page: Add image as metadata

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#70]
Burger image as a dynamic metadata, that way when someone shares a specific Burger link, they get the image as well on their text message, FB, Linkedin, etc.

**Comment by matbalazsi** [comment]
This is a very big change, and difficukt to achieve in single page applications like angular. I'll try but i can't guarantee this one

**Comment by loogart** [comment]
Not top priority at all. We can look at how this works next year or for LPW 2020!
