### ISSUE TITLE
City selector in alphabetical order 

### ISSUE THREAD

**Issue by loogart** [loogart/leburgerweek#72]
Make the list of cities in the modal popup in alphabetical order

![0739DCC6-6BA4-4BCC-80C9-AC90DF6C7652](https://user-images.githubusercontent.com/7881400/63987888-c1209d00-caa7-11e9-832f-9a61e616d5f8.png)

**Comment by matbalazsi** [comment]
This can be done in the dashboard by JP with didplay order
