### ISSUE TITLE
Homepage: NFT section. Update supertitle to "Win $5,000 in Doordash cash!"

### ISSUE THREAD

**Issue by matbalazsi** [loogart/leburgerweek#77]

**Comment by matbalazsi** [comment]
The title was already set. Maybe I missed something
<img width="1241" alt="Screen Shot 2021-08-23 at 8 31 10 PM" src="https://user-images.githubusercontent.com/11080515/130536675-a367f9bc-55ef-4711-b36e-7184ce9d05e1.png">

**Comment by loogart** [comment]
Ah forgot to add the two words "up to" --> "Win up to 5,000..."
