### ISSUE TITLE
Resto page: For franchise - unable to test this user story. Do you have an example?

### ISSUE THREAD

**Issue by matbalazsi** [loogart/leburgerweek#78]
@loogart 
Here is an example

https://staging.leburgerweek.com/restaurant/bergham/view

**Comment by loogart** [comment]
Hey @matbalazsi awesome. Can you remove the address URL from the <summary> tag and include it inside the actual box to avoid that the user clicks on the address by mistake? I would rather they open the box, `<details>` box and then click on the address URL.

<img width="1297" alt="Screen Shot 2021-08-24 at 8 34 32 AM" src="https://user-images.githubusercontent.com/7881400/130617248-6956b992-c000-47aa-8822-c23fb29eddda.png">

**Comment by loogart** [comment]
https://staging.leburgerweek.com/restaurant/industria-pizzeria-bar-laval/view

Can you add the little pin emoji "📍Name" in front of the text inside the `<summary>`

**Comment by matbalazsi** [comment]
Locations do not have a name associated to it.

https://staging.leburgerweek.com/restaurant/industria-pizzeria-bar-laval/view

seems to have not set their locations properly. Many are empty

**Comment by loogart** [comment]
Can we use the address as the name for the `summary` tag? (with the 📍emoji in front of the name)?

**Comment by matbalazsi** [comment]
yes, I'll add the 📍emoji
