### ISSUE TITLE
MODAL LOCATION: Match full bleed design when in desktop mode

### ISSUE THREAD

**Issue by matbalazsi** [loogart/leburgerweek#79]
@loogart 

I need help with this one. 
The col-lg-5 is not growing its' height to match the sibling

<img width="1045" alt="Screen Shot 2021-08-23 at 8 50 49 PM" src="https://user-images.githubusercontent.com/11080515/130538075-dc52e1f9-6668-494b-8672-c77f14eb9f96.png">

**Comment by loogart** [comment]
@matbalazsi I got iiiiiit!
Three things to update:

1. On the `.modal-dialog` element, change the class `.modal-lg` to `.modal-xl` (this will make the text fit better on medium and larger screens.
2. ALSO on the `.modal-dialog` element, ADD the class  `.modal-dialog-centered`
3. Change the class on the parent `.row` holding both columns from `.align-items-center` to `.align-items-stretch` AND remove the class `h-100` from the column holding the image.

Should now look like this on desktop and mobile:

<img width="1427" alt="Screen Shot 2021-08-25 at 11 35 21 AM" src="https://user-images.githubusercontent.com/7881400/130820718-5c38ea20-903c-467a-bd6e-f072efc262b1.png">
<img width="496" alt="Screen Shot 2021-08-25 at 11 35 30 AM" src="https://user-images.githubusercontent.com/7881400/130820750-c69e3160-da05-4efc-a8c5-d65dbddd6ee5.png">
