### ISSUE TITLE
When I log in, I get the blue square animation indefinitely on the /resto/restaurants page

### ISSUE THREAD

**Issue by matbalazsi** [loogart/leburgerweek#85]
can we meetup to review this together?

**Comment by loogart** [comment]
of course! lmk when you wanna chat, ill send a link

**Comment by loogart** [comment]
<img width="1491" alt="Screen Shot 2021-08-24 at 10 28 38 AM" src="https://user-images.githubusercontent.com/7881400/130635108-61da81b5-9a8a-4ed7-a928-e65b8cf05ce0.png">
@matbalazsi this is what I get when I try to access the admin dashboard. Maybe I don't have access?

**Comment by matbalazsi** [comment]
If possible, can you open the error console in dev tools?
Maybe we can see if an error is returned

**Comment by loogart** [comment]
<img width="1598" alt="Screen Shot 2021-08-24 at 11 35 14 AM" src="https://user-images.githubusercontent.com/7881400/130646356-3f2eab14-6d91-4617-bea9-cb4e49535487.png">



Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: Fri Jun 11 2021 11:04:46 GMT-0400 (EDT), _f: undefined, _strict: undefined, _locale: [object Object]
https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:1379209
https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:1398845
https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:1398873
wt@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:1399163
Ct@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:1399542
computeView@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:2650594
ngOnInit@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:2650144
$t@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:859523
Rt@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:859362
Ft@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:859082
uo@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:896077
Fo@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:903180
https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:896805
uo@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:896814
ho@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:897177
Vo@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:903870
Ho@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:904033
detectChanges@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:972076
tick@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:1034354
_loadComponent@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:1034653
bootstrap@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:1034078
forEach@[native code]
_moduleDoBootstrap@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:1031525
https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:1031287
onInvoke@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:1024238
run@https://staging.leburgerweek.com/polyfills-es2015.0cf34c401292ed319d71.js:1:51800
https://staging.leburgerweek.com/polyfills-es2015.0cf34c401292ed319d71.js:1:66536
onInvokeTask@https://staging.leburgerweek.com/main-es2015.dc46e7b41e032693e7a4.js:1:1024058
runTask@https://staging.leburgerweek.com/polyfills-es2015.0cf34c401292ed319d71.js:1:52419
v@https://staging.leburgerweek.com/polyfills-es2015.0cf34c401292ed319d71.js:1:59001
promiseReactionJob@[native code]

**Comment by matbalazsi** [comment]
@loogart 
Can you retry a login? I think it should work

**Comment by loogart** [comment]
works now when I logged in! I see 0 restaurants and no content though, might be normal for the staging site?
<img width="1249" alt="Screen Shot 2021-08-24 at 12 44 47 PM" src="https://user-images.githubusercontent.com/7881400/130656647-451ca187-8aa8-4bc7-bcaf-8d02f7a145ac.png">

**Comment by matbalazsi** [comment]
your user type is resto, and you have no restaurants assigned. 
Do you want to be admin?

**Comment by loogart** [comment]
plzzzzz make me adminnnnn

**Comment by matbalazsi** [comment]
done
